// Code generated by mockery v2.53.5. DO NOT EDIT.

package quotas

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockQuotaChecker is an autogenerated mock type for the QuotaChecker type
type MockQuotaChecker struct {
	mock.Mock
}

type MockQuotaChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuotaChecker) EXPECT() *MockQuotaChecker_Expecter {
	return &MockQuotaChecker_Expecter{mock: &_m.Mock}
}

// CheckResourceQuota provides a mock function with given fields: ctx, namespace
func (_m *MockQuotaChecker) CheckResourceQuota(ctx context.Context, namespace string) (bool, error) {
	ret := _m.Called(ctx, namespace)

	if len(ret) == 0 {
		panic("no return value specified for CheckResourceQuota")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, namespace)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, namespace)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuotaChecker_CheckResourceQuota_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckResourceQuota'
type MockQuotaChecker_CheckResourceQuota_Call struct {
	*mock.Call
}

// CheckResourceQuota is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
func (_e *MockQuotaChecker_Expecter) CheckResourceQuota(ctx interface{}, namespace interface{}) *MockQuotaChecker_CheckResourceQuota_Call {
	return &MockQuotaChecker_CheckResourceQuota_Call{Call: _e.mock.On("CheckResourceQuota", ctx, namespace)}
}

func (_c *MockQuotaChecker_CheckResourceQuota_Call) Run(run func(ctx context.Context, namespace string)) *MockQuotaChecker_CheckResourceQuota_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQuotaChecker_CheckResourceQuota_Call) Return(_a0 bool, _a1 error) *MockQuotaChecker_CheckResourceQuota_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuotaChecker_CheckResourceQuota_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockQuotaChecker_CheckResourceQuota_Call {
	_c.Call.Return(run)
	return _c
}

// OnResourceCreated provides a mock function with given fields: ctx, namespace
func (_m *MockQuotaChecker) OnResourceCreated(ctx context.Context, namespace string) error {
	ret := _m.Called(ctx, namespace)

	if len(ret) == 0 {
		panic("no return value specified for OnResourceCreated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, namespace)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuotaChecker_OnResourceCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnResourceCreated'
type MockQuotaChecker_OnResourceCreated_Call struct {
	*mock.Call
}

// OnResourceCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
func (_e *MockQuotaChecker_Expecter) OnResourceCreated(ctx interface{}, namespace interface{}) *MockQuotaChecker_OnResourceCreated_Call {
	return &MockQuotaChecker_OnResourceCreated_Call{Call: _e.mock.On("OnResourceCreated", ctx, namespace)}
}

func (_c *MockQuotaChecker_OnResourceCreated_Call) Run(run func(ctx context.Context, namespace string)) *MockQuotaChecker_OnResourceCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQuotaChecker_OnResourceCreated_Call) Return(_a0 error) *MockQuotaChecker_OnResourceCreated_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuotaChecker_OnResourceCreated_Call) RunAndReturn(run func(context.Context, string) error) *MockQuotaChecker_OnResourceCreated_Call {
	_c.Call.Return(run)
	return _c
}

// OnResourceDeleted provides a mock function with given fields: ctx, namespace
func (_m *MockQuotaChecker) OnResourceDeleted(ctx context.Context, namespace string) error {
	ret := _m.Called(ctx, namespace)

	if len(ret) == 0 {
		panic("no return value specified for OnResourceDeleted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, namespace)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuotaChecker_OnResourceDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnResourceDeleted'
type MockQuotaChecker_OnResourceDeleted_Call struct {
	*mock.Call
}

// OnResourceDeleted is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
func (_e *MockQuotaChecker_Expecter) OnResourceDeleted(ctx interface{}, namespace interface{}) *MockQuotaChecker_OnResourceDeleted_Call {
	return &MockQuotaChecker_OnResourceDeleted_Call{Call: _e.mock.On("OnResourceDeleted", ctx, namespace)}
}

func (_c *MockQuotaChecker_OnResourceDeleted_Call) Run(run func(ctx context.Context, namespace string)) *MockQuotaChecker_OnResourceDeleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQuotaChecker_OnResourceDeleted_Call) Return(_a0 error) *MockQuotaChecker_OnResourceDeleted_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuotaChecker_OnResourceDeleted_Call) RunAndReturn(run func(context.Context, string) error) *MockQuotaChecker_OnResourceDeleted_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQuotaChecker creates a new instance of MockQuotaChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuotaChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuotaChecker {
	mock := &MockQuotaChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
